### ISSUE TITLE
ZeiselBrainData does not exists

### ISSUE THREAD

**Issue by yeroslaviz** [Bioconductor/OrchestratingSingleCellAnalysis-release#7]
When trying the new scripts in the book, I get the error

```
> library(scRNAseq)
> sce.zeisel <- ZeiselBrainData()
Error in ZeiselBrainData() : could not find function "ZeiselBrainData"
> ZeiselBrainData()
Error in ZeiselBrainData() : could not find function "ZeiselBrainData"
```

Is the package too new or too old?

Any ideas?

Assa

```
> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)
nickname       Planting of a Tree          

> BiocManager::valid()
[1] TRUE
```

**Comment by robertamezquita** [comment]
Too new - you'll need the devel version of Bioconductor. Try running

 BiocManager::install(version = "3.10")

Then it will (hopefully!) work. Thank you for letting me know, we will add
a note that this book is based on the devel branch of Bioconductor (at
least for now)

**Comment by LTLA** [comment]
Just add an inline command pulling out the current version of R on which it was compiled, rather than hard-coding it into the text.

**Comment by yeroslaviz** [comment]
thanks. this has solved the problem.

**Comment by danxfreeman** [comment]
Hi, I've been trying to download sample data for two days now but still get the message `Error in ZeiselBrainData() : could not find function "ZeiselBrainData"`. When I tried downloading the developer version of Bioconductor I get the error `Error: cannot remove prior installation of package ‘BiocGenerics’`. When I succeeded in deleting BiocGenerics through the Finder I got the same error with another package, and then yet another.

Is there an easier way to download a sample sce without messing with so many packages? Maybe I can download it directly from somewhere online?

**Comment by lshep** [comment]
Are you using  Release 3.10  or Devel 3.11?   We experience some technical difficult with the first build of the release experiment data packages -  They should be available after tonight's build.

**Comment by LTLA** [comment]
It works fine right now on BioC-release, even though the version numbers aren't bumped.

```
$ R

R version 3.6.1 Patched (2019-10-31 r77366) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.7.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> BiocManager::install("scRNAseq")
Bioconductor version 3.10 (BiocManager 1.30.9), R 3.6.1 Patched (2019-10-31
  r77366)
Installing package(s) 'scRNAseq'
trying URL 'https://bioconductor.org/packages/3.10/data/experiment/src/contrib/scRNAseq_1.99.8.tar.gz'
Content type 'application/x-gzip' length 282369 bytes (275 KB)
==================================================
downloaded 275 KB

* installing *source* package ‘scRNAseq’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (scRNAseq)

The downloaded source packages are in
	‘/private/var/folders/db/v59jzn_52y39l1w_hrmywbvw0000gp/T/Rtmp5M7nE4/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```

No need to play around with BioC-devel. Some other comments:

> When I succeeded in deleting BiocGenerics through the Finder

You really shouldn't do that unless you know what you're doing. The "correct" way to remove packages is via `remove.packages()`, and if that fails, you have a bigger problem with permissions on your system (e.g., because you don't have write access to the R installation).

> Is there an easier way to download a sample sce without messing with so many packages?

Well, if you're struggling to install _BiocGenerics_, then you pretty much won't be able to do anything in the book (or in Bioconductor, for that matter). That seems a bigger problem than data availability.

> Maybe I can download it directly from somewhere online?

Martin Hemberg has a website that provides SCE objects in serialized form that can be directly downloaded. The problem is that:

- If you couldn't install _BiocGenerics_, then loading the _SingleCellExperiment_ objects will fail.
- You will have to manage your own caching, or accept that you will have to re-download objects every time you re-run your analysis scripts.
- The SCEs were probably created a few releases back and, while I take care to avoid breaking back-compatibility, any overlooked bugs are more likely to manifest with old SCEs than with newly created ones. 

Alternatively, you can always read through [the steps](https://github.com/LTLA/scRNAseq/blob/master/inst/scripts/make-zeisel-brain-data.Rmd) for how I converted the Zeisel dataset into a nicely formatted SCE object. This was definitely not a one-liner.
